version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./:/var/www/html/dacxi_api

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/dacxi_api
    working_dir: /var/www/html/dacxi_api
  
  mysql:
    image: mariadb:10.3
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  cron:
    container_name: cron
    build: ./docker/cron
    volumes:
      - ./:/var/www/html/dacxi_api